### ISSUE TITLE
Launcher icon is transparent

### ISSUE THREAD

**Issue by gkaklas** [felixwiemuth/LinCal#2]
The icon of the app has transparent areas, which makes it difficult to be recognized on devices with dark wallpapers. Maybe filling the inside with white and adding a white border would fix this issue?

**Comment by felixwiemuth** [comment]
This is indeed an issue, however, a completely different icon is planned, so I'll probably not fix this one.

**Comment by jaller94** [comment]
Please consider adding an icon with more contrast soon. I prefer a temporary solution over waiting for months for a neatly designed icon.

**Comment by felixwiemuth** [comment]
You are right, this deserves more priority (and I actually don't plan a very complicated icon anyway). The problem is that I am not aware of how much my app is used - so I focussed on advancing the technology first - but I am happy about the recent growth in discussion activity here. I consider opening a forum where I could get feedback apart from issues and feature requests but unfortunately Github doesn't provide this and I have to find an appropriate solution.
